export const STORAGE_KEY_NAME = {
  ACCESS_TOKEN: 'ACCESS_TOKEN',
  NEW_CREATED_USER: 'NEW_CREATED_USER',
  REMEMBERED_EMAIL: 'REMEMBERED_EMAIL',
  USER_DATA: 'USER_DATA',
}

// Alias para compatibilidade
export const STORAGE_KEYS = STORAGE_KEY_NAME
