/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalyticsDashboard: typeof import('./components/admin/analytics/AnalyticsDashboard.vue')['default']
    AuthLayout: typeof import('./components/UI/AuthLayout/AuthLayout.vue')['default']
    ConfirmEmail: typeof import('./components/auth-kit/components/ConfirmEmail.vue')['default']
    ControlPanelDashboard: typeof import('./components/admin/control-panel/ControlPanelDashboard.vue')['default']
    EngagementHub: typeof import('./components/admin/engagement/EngagementHub.vue')['default']
    EventCategorySelector: typeof import('./components/admin/new-event/EventCategorySelector.vue')['default']
    EventCommentsPanel: typeof import('./components/admin/my-events/EventCommentsPanel.vue')['default']
    EventFaqEditor: typeof import('./components/admin/new-event/EventFaqEditor.vue')['default']
    EventImageUploader: typeof import('./components/admin/new-event/EventImageUploader.vue')['default']
    EventInfoForm: typeof import('./components/admin/new-event/EventInfoForm.vue')['default']
    EventPrivacySettings: typeof import('./components/admin/new-event/EventPrivacySettings.vue')['default']
    FeedbacksCenter: typeof import('./components/admin/feedbacks/FeedbacksCenter.vue')['default']
    HomeDashboard: typeof import('./components/admin/home/HomeDashboard.vue')['default']
    InputLabel: typeof import('./components/UI/inputLabel/InputLabel.vue')['default']
    Interests: typeof import('./components/admin/interests/index.vue')['default']
    InterestsList: typeof import('./components/admin/interests/InterestsList.vue')['default']
    InterestsManager: typeof import('./components/admin/control-panel/InterestsManager.vue')['default']
    LanguageSwitcher: typeof import('./components/LanguageSwitcher.vue')['default']
    LineupManager: typeof import('./components/admin/lineup/LineupManager.vue')['default']
    Login: typeof import('./components/Login/Login.vue')['default']
    MyEventsManager: typeof import('./components/admin/my-events/MyEventsManager.vue')['default']
    NewEvent: typeof import('./components/admin/new-event/index.vue')['default']
    NotificationsCenter: typeof import('./components/admin/notifications/NotificationsCenter.vue')['default']
    ParticipantsManager: typeof import('./components/admin/participants/ParticipantsManager.vue')['default']
    PostEventManager: typeof import('./components/admin/post-event/PostEventManager.vue')['default']
    RequestPassword: typeof import('./components/auth-kit/components/RequestPassword.vue')['default']
    RequestsQueue: typeof import('./components/admin/interests/RequestsQueue.vue')['default']
    ResetPassword: typeof import('./components/auth-kit/components/ResetPassword.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Signup: typeof import('./components/auth-kit/components/Signup.vue')['default']
    Snackbar: typeof import('./components/UI/Snackbar/Snackbar.vue')['default']
    UsersManager: typeof import('./components/admin/users/UsersManager.vue')['default']
    VerifyPin: typeof import('./components/auth-kit/components/VerifyPin.vue')['default']
  }
}
