/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EventCategorySelector: typeof import('./components/admin/EventCategorySelector.vue')['default']
    EventImageUploader: typeof import('./components/admin/EventImageUploader.vue')['default']
    EventInfoForm: typeof import('./components/admin/EventInfoForm.vue')['default']
    EventPrivacySettings: typeof import('./components/admin/EventPrivacySettings.vue')['default']
    LanguageSwitcher: typeof import('./components/LanguageSwitcher.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
