/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/public/admin/control-panel/': RouteRecordInfo<'/public/admin/control-panel/', '/public/admin/control-panel', Record<never, never>, Record<never, never>>,
    '/public/admin/event-edit/[id]': RouteRecordInfo<'/public/admin/event-edit/[id]', '/public/admin/event-edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/public/admin/event-edit/new': RouteRecordInfo<'/public/admin/event-edit/new', '/public/admin/event-edit/new', Record<never, never>, Record<never, never>>,
    '/public/admin/feedbacks/': RouteRecordInfo<'/public/admin/feedbacks/', '/public/admin/feedbacks', Record<never, never>, Record<never, never>>,
    '/public/admin/home/': RouteRecordInfo<'/public/admin/home/', '/public/admin/home', Record<never, never>, Record<never, never>>,
    '/public/admin/interests/': RouteRecordInfo<'/public/admin/interests/', '/public/admin/interests', Record<never, never>, Record<never, never>>,
    '/public/admin/my-events/': RouteRecordInfo<'/public/admin/my-events/', '/public/admin/my-events', Record<never, never>, Record<never, never>>,
    '/public/admin/new-event/': RouteRecordInfo<'/public/admin/new-event/', '/public/admin/new-event', Record<never, never>, Record<never, never>>,
    '/public/admin/users/': RouteRecordInfo<'/public/admin/users/', '/public/admin/users', Record<never, never>, Record<never, never>>,
    '/public/ConfirmEmail/': RouteRecordInfo<'/public/ConfirmEmail/', '/public/ConfirmEmail', Record<never, never>, Record<never, never>>,
    '/public/Interest/': RouteRecordInfo<'/public/Interest/', '/public/Interest', Record<never, never>, Record<never, never>>,
    '/public/login/': RouteRecordInfo<'/public/login/', '/public/login', Record<never, never>, Record<never, never>>,
    '/public/RequestPassword/': RouteRecordInfo<'/public/RequestPassword/', '/public/RequestPassword', Record<never, never>, Record<never, never>>,
    '/public/ResetPassword/': RouteRecordInfo<'/public/ResetPassword/', '/public/ResetPassword', Record<never, never>, Record<never, never>>,
    '/public/Signup/': RouteRecordInfo<'/public/Signup/', '/public/Signup', Record<never, never>, Record<never, never>>,
    '/public/VerifyPin/': RouteRecordInfo<'/public/VerifyPin/', '/public/VerifyPin', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/public/admin/control-panel/index.vue': {
      routes: '/public/admin/control-panel/'
      views: never
    }
    'src/pages/public/admin/event-edit/[id].vue': {
      routes: '/public/admin/event-edit/[id]'
      views: never
    }
    'src/pages/public/admin/event-edit/new.vue': {
      routes: '/public/admin/event-edit/new'
      views: never
    }
    'src/pages/public/admin/feedbacks/index.vue': {
      routes: '/public/admin/feedbacks/'
      views: never
    }
    'src/pages/public/admin/home/index.vue': {
      routes: '/public/admin/home/'
      views: never
    }
    'src/pages/public/admin/interests/index.vue': {
      routes: '/public/admin/interests/'
      views: never
    }
    'src/pages/public/admin/my-events/index.vue': {
      routes: '/public/admin/my-events/'
      views: never
    }
    'src/pages/public/admin/new-event/index.vue': {
      routes: '/public/admin/new-event/'
      views: never
    }
    'src/pages/public/admin/users/index.vue': {
      routes: '/public/admin/users/'
      views: never
    }
    'src/pages/public/ConfirmEmail/index.vue': {
      routes: '/public/ConfirmEmail/'
      views: never
    }
    'src/pages/public/Interest/index.vue': {
      routes: '/public/Interest/'
      views: never
    }
    'src/pages/public/login/index.vue': {
      routes: '/public/login/'
      views: never
    }
    'src/pages/public/RequestPassword/index.vue': {
      routes: '/public/RequestPassword/'
      views: never
    }
    'src/pages/public/ResetPassword/index.vue': {
      routes: '/public/ResetPassword/'
      views: never
    }
    'src/pages/public/Signup/index.vue': {
      routes: '/public/Signup/'
      views: never
    }
    'src/pages/public/VerifyPin/index.vue': {
      routes: '/public/VerifyPin/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
