/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/public/admin/analytics/': RouteRecordInfo<'/public/admin/analytics/', '/public/admin/analytics', Record<never, never>, Record<never, never>>,
    '/public/admin/control-panel/': RouteRecordInfo<'/public/admin/control-panel/', '/public/admin/control-panel', Record<never, never>, Record<never, never>>,
    '/public/admin/dev-tools/': RouteRecordInfo<'/public/admin/dev-tools/', '/public/admin/dev-tools', Record<never, never>, Record<never, never>>,
    '/public/admin/engagement/': RouteRecordInfo<'/public/admin/engagement/', '/public/admin/engagement', Record<never, never>, Record<never, never>>,
    '/public/admin/feedbacks/': RouteRecordInfo<'/public/admin/feedbacks/', '/public/admin/feedbacks', Record<never, never>, Record<never, never>>,
    '/public/admin/home/': RouteRecordInfo<'/public/admin/home/', '/public/admin/home', Record<never, never>, Record<never, never>>,
    '/public/admin/interests/': RouteRecordInfo<'/public/admin/interests/', '/public/admin/interests', Record<never, never>, Record<never, never>>,
    '/public/admin/lineup/': RouteRecordInfo<'/public/admin/lineup/', '/public/admin/lineup', Record<never, never>, Record<never, never>>,
    '/public/admin/new-event/': RouteRecordInfo<'/public/admin/new-event/', '/public/admin/new-event', Record<never, never>, Record<never, never>>,
    '/public/admin/notifications/': RouteRecordInfo<'/public/admin/notifications/', '/public/admin/notifications', Record<never, never>, Record<never, never>>,
    '/public/admin/participants/': RouteRecordInfo<'/public/admin/participants/', '/public/admin/participants', Record<never, never>, Record<never, never>>,
    '/public/admin/post-event/': RouteRecordInfo<'/public/admin/post-event/', '/public/admin/post-event', Record<never, never>, Record<never, never>>,
    '/public/admin/users/': RouteRecordInfo<'/public/admin/users/', '/public/admin/users', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/public/admin/analytics/index.vue': {
      routes: '/public/admin/analytics/'
      views: never
    }
    'src/pages/public/admin/control-panel/index.vue': {
      routes: '/public/admin/control-panel/'
      views: never
    }
    'src/pages/public/admin/dev-tools/index.vue': {
      routes: '/public/admin/dev-tools/'
      views: never
    }
    'src/pages/public/admin/engagement/index.vue': {
      routes: '/public/admin/engagement/'
      views: never
    }
    'src/pages/public/admin/feedbacks/index.vue': {
      routes: '/public/admin/feedbacks/'
      views: never
    }
    'src/pages/public/admin/home/index.vue': {
      routes: '/public/admin/home/'
      views: never
    }
    'src/pages/public/admin/interests/index.vue': {
      routes: '/public/admin/interests/'
      views: never
    }
    'src/pages/public/admin/lineup/index.vue': {
      routes: '/public/admin/lineup/'
      views: never
    }
    'src/pages/public/admin/new-event/index.vue': {
      routes: '/public/admin/new-event/'
      views: never
    }
    'src/pages/public/admin/notifications/index.vue': {
      routes: '/public/admin/notifications/'
      views: never
    }
    'src/pages/public/admin/participants/index.vue': {
      routes: '/public/admin/participants/'
      views: never
    }
    'src/pages/public/admin/post-event/index.vue': {
      routes: '/public/admin/post-event/'
      views: never
    }
    'src/pages/public/admin/users/index.vue': {
      routes: '/public/admin/users/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
